image: "python:3.7"
before_script:
  - python --version
  - pip install -r requirements/base.txt
stages:
  - Static Analysis
  - Test
pylint:
  stage: Static Analysis
  script:
  - pylint torpedo/

pytest:
  stage: Test
  script:
  - pytest